language: node_js

node_js: 0.12

env:
  global:
    - secure: odcV2aW1Jxg5Fi/reDXrZC/sSh6vm3SOeUtxJvB/9ikduLVIIGDlU6Zo4xh6xExvOH5tIE4anPdvKPoitxdXa/xyfAo5eAPoaR9bX1d3mC76ZlrLD+Tj/q91AlftOejNkafP76rl0ukXJPckM4KPna1cy5x22eR+X/CnQHM/y7+fP3t5QnbDLj5082zK09mTx7PnKXfeeGRbmLod1LGFJwOfE6By8fU01LtOuwz/A2mqkC1sLTgGngWtnShD1wqHSCXBmmtxTx2IkZ/UL6esuGaHgipP7F+IXV1JGbO+4IaNooAFDAQ759TI2e0HHLIJE0pNF95vXG9wm3itBITtuREZms+uZNnHGsCHGOxeH3HwBEw2LHtF//u2AczSK6Mqm5SEJEgvCh9RcQYcX1oqpyPi2oPQ3ryp3eboBbhZWWQqdlQxgl3mTvvoKEKT+SPSubgZJLB++RoqwGOXoYjM+7xueaMR82nLiDJ6hMDB7HxmOETEi9UzKOQ/lJ1D9d+IteB1/8z4DUj4ucQJeRwlzWeox34q4Ev8tV/GXWAbVvNJ1sXdDfHTbgt+jcM5VGd/iIc7Dh46ixC1M4tKldoQ2cbZeF0Aks8AEXNLZxEmv3bsX1u9+kR4iKaOpNMD3Tzgjia1GPyvn+B/nl0fa1TZtgR3bTp66YpTIJ4vQtOrYyQ=
    - secure: p92mkOpbu83V5YrtGQseL/xD8mnQqPZRd2GWGUnZmCXDvmCQqvqJ00I/xfJtnSbLkD5OhiYxbjOaXnGJJneL7Pno280AE6wZ4E1lzTi6bhwRkGK9+ltT6cdBd9BCdSZ3rpE3aIViSFZgodonWti5c7WiFHDp1ZZys/90YoGCgNsALn8HWfz4zxVIusWdB1I/CF0qvPkrkYbH6tVG1BGOcjxGteNS/9zYS8tuS0kphVAIa3giTJruYkDMu+HtdArBTQxVA5p9trrA9RWJw0med2XZSeSS2STimcQTg4cMZwV/FlfGAzxkp76jorvQHVeKTekhoTEetcJ/PraxFUq2IgfKWKacd9x6W7WeBxMWjyFu3eXBu3MrvkaVpynxAXCQRqmVtRNFstZdU0ofwQ79j0lezaaNvVHE5wxBTOuhbDZ6l8ozuabUXeu51UQIzdnyYxR3NwSH2f6ZDGxLH9TpJIGf4wK01snH+G5vRNyfsfPm9rkPihywlxaF+2jg4iqwYzgoN0GgJfRWevtnrk2jBGbGug4rNvdzdWerTQwEYVdY+eymxNZQckopbOBndC+vsdJL/bUncfLKVVSYxo0tLkrmVKjJBsKp36/Kgm68tvulop79fQ9GKcoIaKVkJCFXQF1kRW/GDG2N1K1SpMS9RtsdnoWNlZsWuUITtpoWpSU=

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls

notifications:
  email:
    on_failure: change
    on_success: change
